# Generated by Django 5.1.7 on 2025-03-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('parents_name', models.CharField(max_length=255)),
                ('background', models.TextField()),
                ('parents_phone', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('student_class', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
