# Generated by Django 5.1.7 on 2025-03-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seniors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='background',
            new_name='reg_number',
        ),
    ]
